In [1]:
import pandas as pd

In [2]:
j1939 = pd.read_csv('../data/J1939Faults.csv')

C:\Users\sarei\AppData\Local\Temp\ipykernel_22180\3023534108.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  j1939 = pd.read_csv('../data/J1939Faults.csv')

In [3]:
j1939

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,spn,fmi,active,activeTransitionCount,faultValue,EquipmentID,MCTNumber,Latitude,Longitude,LocationTimeStamp
0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,0,111,17,True,2,NaN,1439,105354361,38.857638,-84.626851,2015-02-21 11:34:25.000
1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,11,629,12,True,127,NaN,1439,105354361,38.857638,-84.626851,2015-02-21 11:35:10.000
2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,11,1807,2,False,127,NaN,1369,105336226,41.421250,-87.767361,2015-02-21 11:35:26.000
3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,11,1807,2,True,127,NaN,1369,105336226,41.421018,-87.767361,2015-02-21 11:36:08.000
4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,0,4364,17,False,2,NaN,1674,105427130,38.416481,-89.442638,2015-02-21 11:39:37.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187330,1248454,123904424,2020-03-06 14:00:26.000,Low (Severity Low) Catalyst Tank Level,NaN,04384413*22383729*082218154102*60701732*G1*BGT*,80156139,6X1u17D1500000000,CMMNS,0,1761,17,False,3,NaN,2282,105439740,37.094768,-85.897407,2020-03-06 14:00:21.000
1187331,1248455,123905139,2020-03-06 14:04:23.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,CMMNS,0,1569,31,True,5,NaN,1994,105354084,34.390740,-79.461805,2020-03-06 14:04:59.000
1187332,1248456,123905996,2020-03-06 14:13:38.000,Abnormal Rate of Change Aftertreatment 1 Intak...,NaN,05317106*05100987*050719120655*09401585*G1*BDR*,79880653,6X1u13D1500000000,CMMNS,0,3216,10,True,1,NaN,1850,105336308,34.430370,-84.920509,2020-03-06 14:14:14.000
1187333,1248457,123906113,2020-03-06 14:14:13.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,0,111,18,True,8,NaN,2377,108605700,35.030925,-85.321527,2020-03-06 14:14:49.000
1187334,1248458,123906131,2020-03-06 14:15:34.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,0,111,18,False,8,NaN,2377,108605700,35.027314,-85.323472,2020-03-06 14:15:30.000

In [4]:
j1939[j1939['spn'] == 1569]

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,spn,fmi,active,activeTransitionCount,faultValue,EquipmentID,MCTNumber,Latitude,Longitude,LocationTimeStamp
40,41,990856,2015-02-21 12:06:22.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*04047493*092613211021*09300006*G1*BDR*,79723635,6X1u13D1500000000,CMMNS,0,1569,31,True,5,NaN,1721,105439606,39.051805,-84.560509,2015-02-21 12:06:57.000
249,250,993542,2015-02-21 15:01:49.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*04047493*092613211021*09300006*G1*BDR*,79723635,6X1u13D1500000000,CMMNS,0,1569,31,False,5,NaN,1721,105439606,38.113240,-85.667361,2015-02-21 15:01:45.000
290,291,994045,2015-02-21 15:35:45.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*04047493*092613211021*09300006*G1*BDR*,79723635,6X1u13D1500000000,CMMNS,0,1569,31,True,6,NaN,1721,105439606,37.735185,-85.808101,2015-02-21 15:36:21.000
306,307,994237,2015-02-21 15:51:58.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*04047493*092613211021*09300006*G1*BDR*,79723635,6X1u13D1500000000,CMMNS,0,1569,31,False,6,NaN,1721,105439606,37.540370,-85.880972,2015-02-21 15:51:54.000
340,341,994680,2015-02-21 16:22:24.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*04047493*092613211021*09300006*G1*BDR*,79723635,6X1u13D1500000000,CMMNS,0,1569,31,True,7,NaN,1721,105439606,37.166666,-85.964027,2015-02-21 16:23:00.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1186072,1247196,123246301,2020-03-02 15:51:18.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06009282*100515184137*09400147*G1*BDR*,79897319,6X1u13D1500000000,CMMNS,0,1569,31,True,10,NaN,1855,105317775,33.757453,-84.548611,2020-03-02 15:43:54.000
1186195,1247319,123306956,2020-03-03 06:51:50.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*05088449*051718172255*09401583*G1*BDR*,79875897,6X1u13D1500000000,CMMNS,0,1569,31,False,1,NaN,1827,105464811,36.194907,-83.174953,2020-03-03 06:51:46.000
1186207,1247331,123307779,2020-03-03 06:59:13.000,Condition Exists Engine Protection Torque Derate,NaN,05317106*05088449*051718172255*09401583*G1*BDR*,79875897,6X1u13D1500000000,CMMNS,0,1569,31,False,1,NaN,1827,105464811,36.194861,-83.175000,2020-03-03 07:00:53.000
1186730,1247854,123594250,2020-03-04 16:55:48.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06027162*051718174436*09401683*G1*BDR*,79902732,6X1u13D1500000000,CMMNS,0,1569,31,False,1,NaN,1868,105420782,35.587870,-86.443935,2020-03-04 16:55:44.000
1187331,1248455,123905139,2020-03-06 14:04:23.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,CMMNS,0,1569,31,True,5,NaN,1994,105354084,34.390740,-79.461805,2020-03-06 14:04:59.000

In [5]:
j1939[j1939['spn'] == 5246]

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,spn,fmi,active,activeTransitionCount,faultValue,EquipmentID,MCTNumber,Latitude,Longitude,LocationTimeStamp
45,46,990931,2015-02-21 12:10:51.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,5246,0,True,1,NaN,1395,105349612,36.065972,-86.433425,2015-02-21 12:11:27.000
1918,1919,1007751,2015-02-22 19:44:55.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,5246,0,True,1,NaN,1395,105349612,36.066203,-86.434814,2015-02-22 19:46:27.000
2058,2059,1010486,2015-02-23 04:00:21.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,5246,0,False,1,NaN,1395,105349612,36.066666,-86.434537,2015-02-23 01:06:06.000
2089,2090,1011009,2015-02-23 05:05:44.000,NaN,NaN,05290170*03015749*051914190353*09400015*G1*BDR*,79642446,6X1u13D1500000000,CMMNS,0,5246,0,True,1,NaN,1630,105329900,40.733009,-74.087777,2015-02-23 05:08:23.000
2971,2972,1026305,2015-02-23 15:54:22.000,NaN,NaN,unknown,unknown,unknown,unknown,0,5246,0,True,1,NaN,1487,105369355,28.077361,-81.897083,2015-02-23 15:54:58.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1183032,1244156,121610128,2020-02-19 07:02:33.000,NaN,NaN,05317106*05005224*051718172255*09401583*G1*BDR*,79845785,6X1u13D1500000000,CMMNS,0,5246,0,True,1,NaN,1814,105369518,36.067037,-86.434120,2020-02-19 07:03:09.000
1183684,1244808,121909497,2020-02-21 07:23:44.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,5246,16,True,1,NaN,2211,105329862,36.066296,-86.434305,2020-02-21 07:24:20.000
1184328,1245452,122305094,2020-02-24 15:28:05.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,5246,16,False,1,NaN,2211,105329862,36.066620,-86.434722,2020-02-24 15:28:01.000
1184330,1245454,122305096,2020-02-24 15:27:26.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,5246,0,True,1,NaN,2211,105329862,36.066620,-86.434722,2020-02-24 15:28:02.000
1185275,1246399,122740697,2020-02-27 12:11:33.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,5246,0,False,1,NaN,2211,105329862,36.066296,-86.434490,2020-02-27 12:11:29.000

In [6]:
onboard = pd.read_csv('../data/VehicleDiagnosticOnboardData.csv')

In [7]:
onboard

                Id                      Name        Value  FaultId
0                1                 IgnStatus        False        1
1                2         EngineOilPressure            0        1
2                3      EngineOilTemperature     96.74375        1
3                4        TurboBoostPressure            0        1
4                5                EngineLoad           11        1
...            ...                       ...          ...      ...
12821621  12864020  EngineCoolantTemperature        181.4  1248457
12821622  12864021              ParkingBrake        False  1248457
12821623  12864022    SwitchedBatteryVoltage         14.1  1248457
12821624  12864023               DistanceLtd  28606.65625  1248457
12821625  12864024                LampStatus         1023  1248458

[12821626 rows x 4 columns]

In [8]:
onboard['Name'].unique()

array(['IgnStatus', 'EngineOilPressure', 'EngineOilTemperature',
       'TurboBoostPressure', 'EngineLoad', 'AcceleratorPedal',
       'IntakeManifoldTemperature', 'FuelRate', 'FuelLtd', 'EngineRpm',
       'LampStatus', 'BarometricPressure', 'FuelLevel', 'Speed',
       'EngineTimeLtd', 'CruiseControlSetSpeed', 'CruiseControlActive',
       'EngineCoolantTemperature', 'ParkingBrake',
       'SwitchedBatteryVoltage', 'DistanceLtd', 'Throttle',
       'FuelTemperature', 'ServiceDistance'], dtype=object)

In [9]:
onboard = onboard.pivot(index = 'FaultId',
                        columns = 'Name',
                        values = 'Value')

In [10]:
onboard

Name,AcceleratorPedal,BarometricPressure,CruiseControlActive,CruiseControlSetSpeed,DistanceLtd,EngineCoolantTemperature,EngineLoad,EngineOilPressure,EngineOilTemperature,EngineRpm,...,FuelTemperature,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure
FaultId,,,,,,,,,,,,,,,,,,,,,
1,0,14.21,False,66.48672,423178.7,100.4,11,0,96.74375,0,...,NaN,False,78.8,1023,True,NaN,0,3276.75,NaN,0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,True,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,16639,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1023,NaN,NaN,NaN,NaN,NaN,NaN
1248455,100,14.5,True,64.6226,423937.9,185,51,37.12,211.4937,1310.25,...,32,True,98.6,18431,False,NaN,65.01096,NaN,73.2,7.83
1248456,0,14.355,True,66.48672,465925.4,186.8,62,41.18,212.8438,1340.75,...,NaN,True,91.4,17407,NaN,NaN,66.5741,NaN,100,6.96
1248457,1.6,14.4275,False,67.72946,28606.65625,181.4,0,27.26,221.7312,863.25,...,NaN,True,100.4,1023,False,NaN,11.84489,14.1,100,1.74
1248458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1023,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
both = j1939.merge(onboard,
                  left_on = 'RecordID',
                  right_on = 'FaultId')

In [12]:
both

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,...,FuelTemperature,IgnStatus,IntakeManifoldTemperature,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure
0,1,990349,2015-02-21 10:47:13.000,Low (Severity Low) Engine Coolant Level,NaN,unknown,unknown,unknown,unknown,0,...,NaN,False,78.8,1023,True,NaN,0,3276.75,NaN,0
1,2,990360,2015-02-21 11:34:34.000,NaN,NaN,unknown,unknown,unknown,unknown,11,...,NaN,True,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
2,3,990364,2015-02-21 11:35:31.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,11,...,NaN,NaN,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
3,4,990370,2015-02-21 11:35:33.000,Incorrect Data Steering Wheel Angle,NaN,unknown,unknown,unknown,unknown,11,...,NaN,True,NaN,1279,NaN,NaN,NaN,NaN,NaN,NaN
4,5,990416,2015-02-21 11:39:41.000,NaN,NaN,22281684P01*22357957P01*22362082P01*,13063430,0USA13_13_0415_2238A,VOLVO,0,...,NaN,NaN,NaN,16639,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1187330,1248454,123904424,2020-03-06 14:00:26.000,Low (Severity Low) Catalyst Tank Level,NaN,04384413*22383729*082218154102*60701732*G1*BGT*,80156139,6X1u17D1500000000,CMMNS,0,...,NaN,NaN,NaN,1023,NaN,NaN,NaN,NaN,NaN,NaN
1187331,1248455,123905139,2020-03-06 14:04:23.000,Condition Exists Engine Protection Torque Derate,NaN,04358814*06099720*030816202706*09400153*G1*BDR*,79932020,6X1u13D1500000000,CMMNS,0,...,32,True,98.6,18431,False,NaN,65.01096,NaN,73.2,7.83
1187332,1248456,123905996,2020-03-06 14:13:38.000,Abnormal Rate of Change Aftertreatment 1 Intak...,NaN,05317106*05100987*050719120655*09401585*G1*BDR*,79880653,6X1u13D1500000000,CMMNS,0,...,NaN,True,91.4,17407,NaN,NaN,66.5741,NaN,100,6.96
1187333,1248457,123906113,2020-03-06 14:14:13.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,0,...,NaN,True,100.4,1023,False,NaN,11.84489,14.1,100,1.74
1187334,1248458,123906131,2020-03-06 14:15:34.000,Low (Severity Medium) Engine Coolant Level,NaN,04384413*22544852*090619141107*60701756*G1*BGT*,NaN,NaN,NaN,0,...,NaN,NaN,NaN,1023,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
truck_1395 = both[both['EquipmentID'] == 1395]

In [14]:
truck_1395['spn'].unique()

array([ 111, 3216, 1807, 1045, 1761, 4364,  101,  627,  792,  102, 1569,
        611, 3226, 5031, 5246], dtype=int64)

In [15]:
truck_1395[(truck_1395['EventTimeStamp'] <= '2016-02-18 04:50:10.000') & 
           (truck_1395['EventTimeStamp'] >= '2016-02-17 00:00:00')][['EventTimeStamp','spn', 'fmi', 'active']]

                 EventTimeStamp   spn  fmi  active
380001  2016-02-17 15:22:17.000   111   18    True
380004  2016-02-17 15:24:13.000   111   18   False
380047  2016-02-17 15:43:59.000   111   18    True
380054  2016-02-17 16:15:32.000   111   18   False
380078  2016-02-17 16:37:46.000   111   18    True
380092  2016-02-17 16:58:38.000   111   18   False
380128  2016-02-17 17:25:55.000   111   18    True
380129  2016-02-17 17:28:28.000   111   18   False
380328  2016-02-17 23:28:41.000  3226    4    True
380329  2016-02-17 23:31:04.000  1569   31    True
380330  2016-02-17 23:33:57.000  1569   31   False
380338  2016-02-18 00:01:17.000  1569   31    True
380471  2016-02-18 04:50:10.000  5246    0    True

In [16]:
fault_codes = pd.read_excel('../data/Service Fault Codes_1_0_0_167.xlsx')

C:\Users\sarei\anaconda3\lib\site-packages\openpyxl\worksheet\_reader.py:312: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

In [17]:
fault_codes

,Published in CES 14602,Cummins Fault Code,Revision,PID,SID,MID,J1587 FMI,SPN,J1939 FMI,J2012 Pcode,Lamp Color,Lamp Device,Cummins Description,Algorithm Description
0,Y,111,167,Not Mapped,254,0,12,629,12,P0606,Red,Stop / Shutdown,Engine Control Module Critical Internal Failur...,Error internal to the ECM related to memory ha...
1,Y,112,167,Not Mapped,20,128,7,635,7,Not Mapped,Red,Stop / Shutdown,Engine Timing Actuator Driver Circuit - Mechan...,Mechanical failure in the engine timing actuat...
2,Y,113,167,Not Mapped,20,128,3,635,3,Not Mapped,Amber,Warning,Engine Timing Actuator Driver Circuit - Voltag...,High signal voltage detected at the engine tim...
3,Y,114,167,Not Mapped,20,128,4,635,4,Not Mapped,Amber,Warning,Engine Timing Actuator Driver Circuit - Voltag...,Low voltage detected at the engine timing actu...
4,Y,115,167,190,Not Mapped,Not Mapped,2,612,2,P0008,Red,Stop / Shutdown,Engine Magnetic Speed/Position Lost Both of Tw...,The ECM has detected that the primary and back...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7119,Y,9996,167,Not Mapped,155,0,11,524286,31,Not Mapped,Amber,Warning,Reserved for temporary use - Condition Exists,NaN
7120,Y,9997,167,Not Mapped,155,0,11,524286,31,Not Mapped,Amber,Warning,Reserved for temporary use - Condition Exists,NaN
7121,Y,9998,167,Not Mapped,155,0,11,524286,31,Not Mapped,Amber,Warning,Reserved for temporary use - Condition Exists,NaN
7122,Y,9999,167,Not Mapped,155,0,11,524286,31,Not Mapped,Amber,Warning,Reserved for temporary use - Condition Exists,NaN
7123,Y,12345,167,Not Mapped,155,0,11,524286,31,Not Mapped,Amber,Warning,Reserved for Testing 5 digit FC - Condition Ex...,NaN

In [18]:
fault_codes[fault_codes['SPN'] == 111][['SPN', 'J1939 FMI', 'Cummins Description']]

      SPN  J1939 FMI                                Cummins Description
74    111          3  Coolant Level Sensor 1 Circuit - Voltage Above...
75    111          4  Coolant Level Sensor 1 Circuit - Voltage Below...
76    111         18  Coolant Level - Data Valid But Below Normal Op...
101   111          1  Coolant Level - Data Valid But Below Normal Op...
235   111          2  Coolant Level - Data Erratic, Intermittent, or...
1399  111         16  Coolant Level - Data Valid But Above Normal Op...
1589  111         17  Coolant Level - Data Valid But Below Normal Op...
2243  111         18  Coolant Level - Data Valid But Below Normal Op...
2438  111          9        Coolant Level Sensor - Abnormal Update Rate
2439  111         19  Coolant Level Sensor - Received Network Data i...
3540  111         17  Coolant Level - Data Valid But Below Normal Op...
4552  111          3  Coolant Level Sensor 1 Circuit - Voltage Above...
4553  111          4  Coolant Level Sensor 1 Circuit - Voltage Below...

In [19]:
fault_codes = fault_codes[['SPN',
                           'J1939 FMI',
                           'Cummins Description']].drop_duplicates()

In [20]:
both_fault = both.merge(fault_codes,
                        left_on = ['spn', 'fmi'],
                        right_on = ['SPN', 'J1939 FMI'])

In [21]:
truck_1395 = both_fault[both_fault['EquipmentID'] == 1395]

In [22]:
truck_1395

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,...,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,SPN,J1939 FMI,Cummins Description
10123,34428,2092168,2015-04-26 01:42:41.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,NaN,NaN,NaN,NaN,111,17,Coolant Level - Data Valid But Below Normal Op...
10124,34429,2092171,2015-04-26 01:46:16.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,NaN,NaN,NaN,NaN,111,17,Coolant Level - Data Valid But Below Normal Op...
28635,94774,3069815,2015-06-21 18:11:30.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,9.611835,3276.75,NaN,5.8,111,17,Coolant Level - Data Valid But Below Normal Op...
28636,94776,3069824,2015-06-21 19:17:39.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,NaN,NaN,NaN,NaN,111,17,Coolant Level - Data Valid But Below Normal Op...
29385,96956,3108501,2015-06-23 17:07:50.000,Low (Severity Low) Engine Coolant Level,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,34.29192,3276.75,NaN,19.14,111,17,Coolant Level - Data Valid But Below Normal Op...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
650032,376001,7337811,2016-02-09 05:14:37.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,5031,10,Aftertreatment 1 Outlet NOx Sensor Heater - Ab...
650033,380413,7404325,2016-02-11 20:28:03.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,17407,NaN,NaN,5.796228,NaN,NaN,0.58,5031,10,Aftertreatment 1 Outlet NOx Sensor Heater - Ab...
650034,389115,7543931,2016-02-18 20:24:56.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,5119,NaN,NaN,NaN,NaN,NaN,NaN,5031,10,Aftertreatment 1 Outlet NOx Sensor Heater - Ab...
650035,389190,7545415,2016-02-19 00:21:05.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,17407,NaN,NaN,4.51465,NaN,NaN,2.03,5031,10,Aftertreatment 1 Outlet NOx Sensor Heater - Ab...
650039,406607,7837842,2016-03-05 00:42:10.000,NaN,NaN,04993120*00027849*082113134117*07700053*I0*BBZ*,79464664,6X1u10D1500000000,CMMNS,0,...,1023,NaN,NaN,NaN,NaN,NaN,NaN,5031,10,Aftertreatment 1 Outlet NOx Sensor Heater - Ab...

In [23]:
truck_1395[(truck_1395['EventTimeStamp'] <= '2016-02-18 04:50:10.000') & 
           (truck_1395['EventTimeStamp'] >= '2016-02-17 00:00:00')][['EventTimeStamp',
                                                                     'spn',
                                                                     'fmi',
                                                                     'active',
                                                                     'Cummins Description']].sort_values('EventTimeStamp')

,EventTimeStamp,spn,fmi,active,Cummins Description
462482,2016-02-17 15:22:17.000,111,18,True,Coolant Level - Data Valid But Below Normal Op...
462483,2016-02-17 15:24:13.000,111,18,False,Coolant Level - Data Valid But Below Normal Op...
462486,2016-02-17 15:43:59.000,111,18,True,Coolant Level - Data Valid But Below Normal Op...
462487,2016-02-17 16:15:32.000,111,18,False,Coolant Level - Data Valid But Below Normal Op...
462488,2016-02-17 16:37:46.000,111,18,True,Coolant Level - Data Valid But Below Normal Op...
462489,2016-02-17 16:58:38.000,111,18,False,Coolant Level - Data Valid But Below Normal Op...
462490,2016-02-17 17:25:55.000,111,18,True,Coolant Level - Data Valid But Below Normal Op...
462491,2016-02-17 17:28:28.000,111,18,False,Coolant Level - Data Valid But Below Normal Op...
541276,2016-02-17 23:28:41.000,3226,4,True,Aftertreatment 1 Outlet NOx Sensor Circuit - V...
446769,2016-02-17 23:31:04.000,1569,31,True,Engine Protection Torque Derate - Condition Ex...
446770,2016-02-17 23:33:57.000,1569,31,False,Engine Protection Torque Derate - Condition Ex...
446771,2016-02-18 00:01:17.000,1569,31,True,Engine Protection Torque Derate - Condition Ex...
455107,2016-02-18 04:50:10.000,5246,0,True,Aftertreatment SCR Operator Inducement - Data ...

In [28]:
trucks = both_fault[both_fault['spn'] == 5246]['EquipmentID'].unique()

In [29]:
truck_2211 = both_fault[both_fault['EquipmentID'] == 2211]

In [30]:
truck_2211

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,...,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,SPN,J1939 FMI,Cummins Description
441134,1238842,119630338,2020-02-04 06:50:39.000,High Voltage (Fuel Level),NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,22527,True,NaN,0,NaN,100,0,96,3,Fuel Level (Main Tank) Sensor Circuit - Voltag...
441135,1238846,119630561,2020-02-04 06:52:49.000,High Voltage (Fuel Level),NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,96,3,Fuel Level (Main Tank) Sensor Circuit - Voltag...
455672,1238721,119578297,2020-02-03 16:34:21.000,NaN,NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,22527,True,NaN,0,NaN,100,0.58,5246,0,Aftertreatment SCR Operator Inducement - Data ...
455673,1238724,119579957,2020-02-03 16:47:40.000,NaN,NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,5246,0,Aftertreatment SCR Operator Inducement - Data ...
455682,1245454,122305096,2020-02-24 15:27:26.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,5119,True,NaN,0,NaN,100,0,5246,0,Aftertreatment SCR Operator Inducement - Data ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
666141,1245452,122305094,2020-02-24 15:28:05.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,5119,NaN,NaN,NaN,NaN,NaN,NaN,5246,16,Aftertreatment SCR Operator Inducement Severit...
671559,1242357,121154652,2020-02-15 12:01:03.000,Abnormal Update Rate Catalyst Tank Temperature,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,18431,True,NaN,0,NaN,100,0,3031,9,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
671560,1242373,121158107,2020-02-15 12:39:00.000,Abnormal Update Rate Catalyst Tank Temperature,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,3031,9,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
671565,1244308,121674499,2020-02-19 13:05:05.000,Abnormal Update Rate Catalyst Tank Temperature,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,18431,True,NaN,0,NaN,100,0,3031,9,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
671566,1244317,121676641,2020-02-19 13:14:27.000,Abnormal Update Rate Catalyst Tank Temperature,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,1023,NaN,NaN,NaN,NaN,NaN,NaN,3031,9,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...

In [33]:
truck_2211[(truck_2211['spn'] == 5246) & (truck_2211['fmi'] == 0)]

,RecordID,ESS_Id,EventTimeStamp,eventDescription,actionDescription,ecuSoftwareVersion,ecuSerialNumber,ecuModel,ecuMake,ecuSource,...,LampStatus,ParkingBrake,ServiceDistance,Speed,SwitchedBatteryVoltage,Throttle,TurboBoostPressure,SPN,J1939 FMI,Cummins Description
455672,1238721,119578297,2020-02-03 16:34:21.000,NaN,NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,22527,True,NaN,0,NaN,100,0.58,5246,0,Aftertreatment SCR Operator Inducement - Data ...
455673,1238724,119579957,2020-02-03 16:47:40.000,NaN,NaN,04384413*22246857*121817205924*60701721*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,5246,0,Aftertreatment SCR Operator Inducement - Data ...
455682,1245454,122305096,2020-02-24 15:27:26.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,5119,True,NaN,0,NaN,100,0,5246,0,Aftertreatment SCR Operator Inducement - Data ...
455683,1246399,122740697,2020-02-27 12:11:33.000,NaN,NaN,04384413*22246857*090619141107*60701756*G1*BGT*,80092582,6X1u17D1500000000,CMMNS,0,...,17407,NaN,NaN,NaN,NaN,NaN,NaN,5246,0,Aftertreatment SCR Operator Inducement - Data ...

In [40]:
truck_2211[(truck_2211['EventTimeStamp'] <= '2020-02-27 12:11:33.000') & 
           (truck_2211['EventTimeStamp'] >= '2020-02-01 00:00:00')][['EventTimeStamp',
                                                                     'spn',
                                                                     'fmi',
                                                                     'active',
                                                                     'Cummins Description']].sort_values('EventTimeStamp')

,EventTimeStamp,spn,fmi,active,Cummins Description
632705,2020-02-03 10:37:54.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
666138,2020-02-03 15:46:46.000,5246,16,True,Aftertreatment SCR Operator Inducement Severit...
455672,2020-02-03 16:34:21.000,5246,0,True,Aftertreatment SCR Operator Inducement - Data ...
455673,2020-02-03 16:47:40.000,5246,0,False,Aftertreatment SCR Operator Inducement - Data ...
666139,2020-02-03 16:47:58.000,5246,16,False,Aftertreatment SCR Operator Inducement Severit...
535966,2020-02-04 06:43:14.000,639,2,True,"J1939 Network #1 - Data Erratic, Intermittent,..."
638401,2020-02-04 06:50:35.000,2623,4,True,Accelerator Pedal or Lever Position Sensor 2 C...
641148,2020-02-04 06:50:35.000,91,4,True,Accelerator Pedal or Lever Position Sensor 1 C...
441134,2020-02-04 06:50:39.000,96,3,True,Fuel Level (Main Tank) Sensor Circuit - Voltag...
535967,2020-02-04 06:52:48.000,639,2,False,"J1939 Network #1 - Data Erratic, Intermittent,..."
638402,2020-02-04 06:52:49.000,2623,4,False,Accelerator Pedal or Lever Position Sensor 2 C...
441135,2020-02-04 06:52:49.000,96,3,False,Fuel Level (Main Tank) Sensor Circuit - Voltag...
641149,2020-02-04 06:52:49.000,91,4,False,Accelerator Pedal or Lever Position Sensor 1 C...
632715,2020-02-15 11:41:33.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632716,2020-02-15 11:51:52.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
659266,2020-02-15 12:01:02.000,1761,19,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
613387,2020-02-15 12:01:03.000,1761,9,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
671559,2020-02-15 12:01:03.000,3031,9,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
643726,2020-02-15 12:15:25.000,91,8,True,Accelerator Pedal or Lever Position Sensor 1 C...
613388,2020-02-15 12:28:25.000,1761,9,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
659267,2020-02-15 12:28:27.000,1761,19,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
671560,2020-02-15 12:39:00.000,3031,9,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
643727,2020-02-15 12:39:00.000,91,8,False,Accelerator Pedal or Lever Position Sensor 1 C...
632717,2020-02-15 12:42:21.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632724,2020-02-19 05:43:54.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632725,2020-02-19 06:30:37.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632726,2020-02-19 06:41:06.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
602241,2020-02-19 12:12:03.000,96,4,True,Fuel Level (Main Tank) Sensor Circuit - Voltag...
602242,2020-02-19 12:16:53.000,96,4,False,Fuel Level (Main Tank) Sensor Circuit - Voltag...
632727,2020-02-19 12:17:32.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632728,2020-02-19 12:20:09.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632729,2020-02-19 12:42:17.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632730,2020-02-19 12:43:54.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
659270,2020-02-19 13:05:04.000,1761,19,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
613391,2020-02-19 13:05:05.000,1761,9,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
671565,2020-02-19 13:05:05.000,3031,9,True,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
659271,2020-02-19 13:10:05.000,1761,19,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
613392,2020-02-19 13:10:05.000,1761,9,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Lev...
671566,2020-02-19 13:14:27.000,3031,9,False,Aftertreatment 1 Diesel Exhaust Fluid Tank Tem...
632731,2020-02-19 13:14:27.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
632732,2020-02-19 13:19:28.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
666140,2020-02-21 07:23:44.000,5246,16,True,Aftertreatment SCR Operator Inducement Severit...
455682,2020-02-24 15:27:26.000,5246,0,True,Aftertreatment SCR Operator Inducement - Data ...
666141,2020-02-24 15:28:05.000,5246,16,False,Aftertreatment SCR Operator Inducement Severit...
632736,2020-02-24 15:28:05.000,5394,5,False,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
610806,2020-02-27 08:42:47.000,168,1,True,Battery 1 Voltage - Data Valid But Below Norma...
632740,2020-02-27 12:10:53.000,5394,5,True,Aftertreatment 1 Diesel Exhaust Fluid Dosing V...
455683,2020-02-27 12:11:33.000,5246,0,False,Aftertreatment SCR Operator Inducement - Data ...